#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Load gpgsync module and resources from the source code tree
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.gpgsync_dev = True

import gpgsync
gpgsync.main()
